import {
  SiTypescript, SiJavascript, SiPython, SiPostgresql, SiReact, SiNextdotjs, SiTailwindcss, SiShadcnui,
  SiVite, SiGreensock, SiThreedotjs, SiNodedotjs, SiNestjs, SiExpress, SiFastify, SiSwagger, SiStripe,
  SiGooglegemini, SiMysql, SiMongodb, SiPrisma, SiPandas, SiJest, SiVitest, SiZod, SiJsonwebtokens,
  SiDocker, SiGit, SiGithubactions, SiVercel, SiEslint, SiPrettier, SiFigma, SiOpengl, SiOpenid,
  SiHtml5, SiCss3, SiBootstrap,
} from 'react-icons/si';

// Logos monocromáticos (currentColor) por chave de toolKey(); quem não tem logo ganha a inicial.
// Os certificados usam o mesmo mapa (campo icon), para o site inteiro ter um só estilo de logo
export const TOOL_ICONS = {
  typescript: SiTypescript,
  javascript: SiJavascript,
  python: SiPython,
  sql: SiPostgresql,
  glsl: SiOpengl,
  react: SiReact,
  'next.js': SiNextdotjs,
  tailwindcss: SiTailwindcss,
  shadcnui: SiShadcnui,
  vite: SiVite,
  gsap: SiGreensock,
  'three.js': SiThreedotjs,
  reactthreefiber: SiThreedotjs,
  figma: SiFigma,
  'node.js': SiNodedotjs,
  nestjs: SiNestjs,
  express: SiExpress,
  fastify: SiFastify,
  swagger: SiSwagger,
  stripe: SiStripe,
  gemini: SiGooglegemini,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  prisma: SiPrisma,
  pandas: SiPandas,
  jest: SiJest,
  vitest: SiVitest,
  zod: SiZod,
  jwt: SiJsonwebtokens,
  oauth: SiOpenid,
  docker: SiDocker,
  git: SiGit,
  githubactions: SiGithubactions,
  vercel: SiVercel,
  eslint: SiEslint,
  prettier: SiPrettier,
  // Usados também pelos certificados
  html5: SiHtml5,
  css3: SiCss3,
  bootstrap: SiBootstrap,
};
